# xiaoyuan100 — 100 条音频
workspace: xiaoyuan100
data_dir: data_dir/xiaoyuan100

postprocess:
  handle_unexpected_sil: false
  filter_short_phone_sec: 0.005
  filter_long_word_sec: 1.5
  filter_min_phone_coverage: 0.25
  filter_edge_gap_sec: 0.35
